### ISSUE TITLE
Is it malware?

### ISSUE THREAD

**Issue by ichirugame** [MarkManFlame55/DragonRevamped#1]
If you check the plug-in you created with MCAntiMalware, it will be called malware.
[AntiMalware] [03:39:40] [DETECTED]: plugins/DragonRevamped-1.0-shaded.jar MIGHT be infected with Spigot.INFO.Non-Vanilla Enchantment.A Class Path: org/markmanflame55/dragonrevamped/Utils/DragonMinions ; SourceFile/Line DragonMinions.java/43

**Comment by MarkManFlame55** [comment]
I didn't desing this like Malware(I don't even know how to work with system variables or system files) and if you read that message you that the supposed "malware" it's a non-vanilla enchantment, and you can check that exact line here to see that exact line applying sharpness 8 to the minions weapon

**Comment by ichirugame** [comment]
Sorry for calling it malware.
Is this plugin compatible with 1.16.5?

**Comment by MarkManFlame55** [comment]
no srry. It uses 1.20 features

**Comment by ichirugame** [comment]
I see.
I hope you support it.

**Comment by ichirugame** [comment]
Thank you.
It would be great if you could support a wider range of versions, such as 1.16.5.

**Comment by MarkManFlame55** [comment]
More of my future plugins i´ll make it with this wider range for sure. But this exactly has some features that I liked a lot involving things like Block Displays and Trims. If I see a lot of people that want it in earlier versions i´ll make another plugin with better things. Thanks for feedback :D

**Comment by ichirugame** [comment]
I forgot to ask a few things.
What enhancements are included in the Ender Dragon?
For example, the ender dragon automatically heals without endocrystals, etc.

**Comment by MarkManFlame55** [comment]
In the plugins there's a Guide Book that you can get using /dragon guide showing everything new in the bossfight

**Comment by ichirugame** [comment]
I think it is very good.
Thank you.
